### ISSUE TITLE
"SMS generic failure" Error

### ISSUE THREAD

**Issue by fierytechknowhows** [lukeaschenbrenner/TxtNet-Browser#3] opened 2022-10-13 13:41 UTC
I am having problems too. I can use unstop in the Samsung messages app and txtnet browser and I get a response back from the server. But when I try to go to any website it just says loading and gives an "SMS generic failure" error and I don't receive any SMS messages for the url. I'm wondering if anyone else is getting the same "SMS generic failure" message since I haven't seen it anywhere else on here.

**Comment by lukeaschenbrenner** [comment] 2022-11-15 20:18
Hello,
Sorry for the late reply. Can you confirm whether or not the initial request message is sent or not? If it is not sent, can you attempt to manually send the message with the following contents using your default SMS app, with TxtNet browser open in the background? I am curious if the server response is received and parsed at all.

`àà@(:ÆS3SSøöv)8G7G1ø1YakfÅ+6,¥*Ç)3Um#&:U¥;¡Càààààààààààààààààààààààààààààààààààààààààààààààààààààààààààààààààààààààààààààààààààààààààààààààààààààààààààààààààààà`

Please note that as of right now the server is down, I am working on getting it up ASAP once I fund more Twilio credits in the account. Thanks for your patience and I appreciate the help resolving this bug.

**Comment by fierytechknowhows** [comment] 2022-11-15 20:44
![Screenshot_20221115-144217_Messages](https://user-images.githubusercontent.com/19141632/202021420-b0c5b2c7-880c-45c3-9ed0-35297c97322a.jpg) There is no response from the server when I send what you suggested but stop and unstop works.

**Comment by lukeaschenbrenner** [comment] 2022-11-15 23:35
Thank you for the reply. I will start the server in the next couple days and let you know ASAP when it is ready so that you can retry.

**Comment by fierytechknowhows** [comment] 2022-11-16 07:42
Ok thanks I hope it works and by the way I love this idea of being able to browse the web over sms when an internet connection isn't available.

**Comment by lukeaschenbrenner** [comment] 2022-11-17 16:46
Thanks, it is a pretty cool concept! The server should be back up for the time being. Please retry the sending the message with TxtNet Browser open in the background and let me know how it goes. It's likely I will need to send you a debug version of the app in order to figure out exactly where the point of failure is, but this is a good first step.

**Comment by lukeaschenbrenner** [comment] 2022-11-18 01:37
That's good to know. I'll work on getting that sent out to you sometime soon. Thanks for the help thus far!

**Comment by fierytechknowhows** [comment] 2022-11-18 02:31
How will you send the apk?

**Comment by lukeaschenbrenner** [comment] 2022-11-18 02:36
I'll probably just throw it into a github repo or attach a google drive link, hopefully one of those methods will work for you?

**Comment by fierytechknowhows** [comment] 2022-11-18 02:39
Ya either will work

**Comment by fierytechknowhows** [comment] 2022-11-18 17:52
The google drive option would probably be faster though.

**Comment by fierytechknowhows** [comment] 2022-11-21 13:33
So which method will you do?

**Comment by lukeaschenbrenner** [comment] 2022-11-21 15:05
Sorry for the delays. I'll work on getting a Google Drive link to you later today, if possible.

**Comment by fierytechknowhows** [comment] 2022-11-21 15:48
Oh ok thanks, I hope that version of the app works.

**Comment by lukeaschenbrenner** [comment] 2022-11-22 01:22
@fierytechknowhows Hello,
I modified the app to attempt to log the specific error code associated with the "SMS generic failure" bug. This should greatly assist in diagnosing the root cause of the problem. Please delete any current version of the app on your phone and install this APK:
[https://drive.google.com/file/d/195xcrRNLUR9h_kfbM1UZP2oIfZEwYGfe/view](https://drive.google.com/file/d/195xcrRNLUR9h_kfbM1UZP2oIfZEwYGfe/view)
When you encounter the error again, a file should be written to the path " /storage/emulated/0/Android/data/com.txtnet.txtnetbrowser/logFile.txt ". On recent Android versions, you may need to use an app like [Explorer](https://play.google.com/store/apps/details?id=com.speedsoftware.explorer) to be able to access this folder. Please let me know what the contents of this file are!

**Comment by fierytechknowhows** [comment] 2022-11-22 02:46
In the log file there was this
2022-11-21 20:44:27.770 I/: Unknown Error code: -1. This should never happen!

**Comment by lukeaschenbrenner** [comment] 2022-11-22 15:47
Well... That's exactly what I was hoping not to see haha. Looks like this is going to be harder to fix than I anticipated. Can you please tell me the exact model number of your phone (probably located in Settings -> About Phone) and Android version? In the coming weeks I will work on creating an app that tests a few different methods of sending SMS, and hopefully at least one of those methods will work. Thanks for your help so far.

**Comment by fierytechknowhows** [comment] 2022-12-07 02:53
have you made any progress on creating an app that tests different methods of sending SMS?

**Comment by fierytechknowhows** [comment] 2022-12-12 18:27
@lukeaschenbrenner Hi it's been a while and I'm wondering if you're still monitoring this page and also if you have made any progress on creating an app that tests different methods of sending SMS. I hope you are able to find a method of sending SMS that works

**Comment by lukeaschenbrenner** [comment] 2022-12-13 04:36
@fierytechknowhows Life has gotten busy for me lately with college final exams, but I've finally finished my last exam. I'm shifting focus back to this project again and I'll have an update for you soon! Thanks for your continued interest.

**Comment by fierytechknowhows** [comment] 2023-02-01 19:21
Hi it has been a while again and I was wondering what the status is on creating an app that tests different methods of sending SMS. Oh by the way I still have the same S20 FE 5G but I have recieved and updated to android 13 now just in case that makes a difference in how you create an app version that tests different SMS methods.

**Comment by lukeaschenbrenner** [comment] 2023-02-02 04:44
Hi @fierytechknowhows , I appreciate your patience. I had taken up a pretty large undertaking working on a major server update, so most of my time this past month has been devoted to getting the compression and decompression library functional on Android. But I really do appreciate your willingness to get this working! If everything goes according to plan I should have an APK for you to test around this weekend. I have looked into the problem a little bit more, is your phone by any chance a dual-sim? (Can you find your phone's model number in settings?)

**Comment by fierytechknowhows** [comment] 2023-02-03 19:49
My model is the U.S. S20 FE 5G (SM-G781V) with a single sim and not the international S20 FE 4G (SM-G780V) which is a dual sim. I hope the apk works when you send it this weekend. I appreciate your effort in this project.

**Comment by lukeaschenbrenner** [comment] 2023-02-06 04:34
Interesting. I have seen that the issue likely arises due to one of three things when no error code is supplied:
1) The phone is dual-sim with no default SIM selected
2) The message being sent is too long (this should never occur in TxtNet Browser because messages are multipart)
3) The message contains unsupported characters

To test the possibility of options 2 and 3, I've whipped up a quick sample app. All it does is send two text messages to a US Google Voice number I have registered when you press the button. Let me know what your results are and we can go from there:

[https://drive.google.com/file/d/1aBC2tQ75RcAduY0MF390i4YvKWum87_k/view](https://drive.google.com/file/d/1aBC2tQ75RcAduY0MF390i4YvKWum87_k/view)

Thank you for waiting and continuing to help.

**Comment by fierytechknowhows** [comment] 2023-02-06 13:37
It sent "test message" twice to the google voice number.

**Comment by lukeaschenbrenner** [comment] 2023-02-06 20:54
Are you still getting the SMS generic failure error for the Google voice number, or is it failing silently?

**Comment by fierytechknowhows** [comment] 2023-02-06 21:39
Yes it still gives the same error even with that number.

**Comment by lukeaschenbrenner** [comment] 2023-02-06 21:57
Okay, thanks for testing. I'm going to update the SMS test app to perform some tests on certain strings in order to see what your carrier is rejecting. I will get back to you soon with that updated APK. Given your phone's model number, you have service with Verizon, correct? IIRC another person with this issue was also on Verizon with a Samsung.

**Comment by fierytechknowhows** [comment] 2023-02-06 21:59
Yep my carrier is Verizon.

**Comment by lukeaschenbrenner** [comment] 2023-02-09 04:35
@fierytechknowhows I have a new, exciting (read: highly unstable!) build of the SMS Test app for you to test. It will attempt to send about 125 text messages (each separate) to a number you specify (you can leave it at default, it makes no difference as long as the number is real). Please note that due to Android's OS structure, you will likely see this message as things progress:

[https://github.com/lukeaschenbrenner/2345675432/blob/master/SMS_Test_Sender.png?raw=true](https://github.com/lukeaschenbrenner/2345675432/blob/master/SMS_Test_Sender.png?raw=true)

Simply keep pressing allow until the job is over. It might take a couple minutes to get through.

Hopefully the app doesn't crash, but I can't make any guarantees. When it is over, please screenshot the list of failed characters. (there isn't a direct indication that it's over, but when characters stop showing up for a while, it's probably done.)

https://drive.google.com/file/d/1OOjkFpJDEtIXNncR3K2MPoIZ96hKdG8b/view

**Comment by fierytechknowhows** [comment] 2023-02-09 18:43
None of the characters failed to send they all successfully sent.

**Comment by lukeaschenbrenner** [comment] 2023-02-09 19:53
@fierytechknowhows Thank you for the report. It seems like your carrier has no issues sending each character individually - so it must be some combination of characters that trips it up. I've created a new build of the tester that has 12 crafted messages to send, which should hopefully give us some more insight. 3 of the 12 are taken directly from a TxtNet browser server response at 160 characters, so we should see them fail to send if everything is consistent.

I updated the [Google Drive link](https://drive.google.com/file/d/1OOjkFpJDEtIXNncR3K2MPoIZ96hKdG8b/view) with the newest apk. Thanks again for helping test.

**Comment by fierytechknowhows** [comment] 2023-02-09 21:34
These are the failed messages from the app and this is what was sent from the app. It sent a weird blank message. It happens every time so its not a one time glitch. I also tried changing the number to one of my other numbers and it received the other 2 but not the blank one.
![Screenshot_20230209_150402_SMS Test Sender](https://user-images.githubusercontent.com/19141632/217944263-c9c8266f-0ebd-4fa7-bb77-1dd113294ab2.jpg)
![Screenshot_20230209_150425_Messages](https://user-images.githubusercontent.com/19141632/217944271-41c77493-2668-4f48-bffa-e9c896fc44b2.jpg)

**Comment by lukeaschenbrenner** [comment] 2023-02-09 22:01
Interesting, thanks for the report. I was seeing the same behavior with the blank message - that's just the newline character. It seems that most carriers don't deliver it, which isn't entirely unheard of. In the original development of the app, I had to avoid placing a newline at the end of a message because carriers tend to remove trailing newlines.

As far as the failed characters go, it seems like there is some combination of characters that your carrier is simply refusing to send. If you can, try to send the three sequences of characters [here](https://pastebin.com/9UbsmWmC)  to a phone number using your default SMS app. Before you send each message, verify that the character limit is full (hopefully your SMS app shows the character limit near the text input, it should read something like 160/160). If all three messages succeed to send and are received exactly the same as they were sent (please check on this too!) Then I will modify the test SMS sender app to test one of these failed strings by beginning at one character and slowly increasing the character count until the full string is sent. This should give us a better idea of what is breaking and when. If any of the 3 strings fails to send, you could try to do this yourself by deleting characters until it does send. If you see that when you paste the message it exceeds the character limit (shows anything over 160 characters or indicates that the message is being split), also let me know.

**Comment by lukeaschenbrenner** [comment] 2023-02-09 22:02
Oops, the first string in the pastebin has an extra whitespace prepended to the text. Please make sure not to copy that.

**Comment by fierytechknowhows** [comment] 2023-02-09 23:06
None of them failed to send and they all checked out as the exact same on both ends. But i did notice that each one is being split up into 3 sms messages. It shows 41/3 for all 3 of them.

**Comment by lukeaschenbrenner** [comment] 2023-02-10 01:39
Ah... That could be the issue. I'll get back to you about a potential solution, but it sounds like at least one character is causing your phone to consider that message as 3 separate messages. I won't get into the technical side of things but if you've ever inserted an emoji in a text you'll see that the amount of characters per sms goes down from 160 to 70. For some bizarre reason, your phone is interpreting one of the characters as an emoji-type character. I can try to develop a test app that manually tries to send texts if 160 characters with each character filling the entire text. Alternatively, if you have time, you could try to remove characters from the text field until you see the left side of the character counter change significantly. Thanks for the report!

**Comment by fierytechknowhows** [comment] 2023-02-10 05:50
Yes you should create a test app that sends 160 of each character

**Comment by lukeaschenbrenner** [comment] 2023-02-10 23:57
> Yes you should create a test app that sends 160 of each character

@fierytechknowhows [https://drive.google.com/file/d/1OOjkFpJDEtIXNncR3K2MPoIZ96hKdG8b/view?usp=sharing](Done.) In order to avoid blocking the main thread, the failed characters won't appear until they are all completely sent. I tested on my end and received 114 SMS messages (out of 115 possible, due to recipient not parsing the newline character which is entirely ok). Let me know how it goes.

**Comment by fierytechknowhows** [comment] 2023-02-11 01:32
There were only 86 messages but it didn't show the failed characters

**Comment by lukeaschenbrenner** [comment] 2023-02-11 02:36
I've found the bug behind not displaying characters - I didn't catch it originally because I had no unsent messages on my phone. Please update your app (using the same link above, new version uploaded). Thanks again!

**Comment by fierytechknowhows** [comment] 2023-02-11 13:48
These were the failed characters: £, ¥, è

**Comment by lukeaschenbrenner** [comment] 2023-02-11 17:51
Interesting. Thank you very much for helping me narrow the issue down. Just to confirm, can you tell me how many texts your default SMS app considers each character when copied 160 times? You can paste the text from [here](https://pastebin.com/raw/1hwys9Ln) if that helps. This is likely an issue that I'll have to contact Samsung themselves about in order to resolve... I'm not sure about the scale of this issue though as far as how many models of Samsung phones it affects.

**Comment by fierytechknowhows** [comment] 2023-02-11 18:10
It showed 41/3 which is 2 messages and 41 characters left for the 3rd message

**Comment by lukeaschenbrenner** [comment] 2023-02-11 20:24
Thank you for testing. I am almost completely confident that this is an OS-level issue, so I will try to get in contact with Samsung to see if they can issue a software update. Before I do, just to make absolutely sure this isn't another issue, can you please download [Messages by Google](https://play.google.com/store/apps/details?id=com.google.android.apps.messaging) and set it as your default SMS app? Then, please try to paste the 3 messages you just tried and verify that messages by Google also shows 41/3. If it shows "0", please try to send the message and verify that the message sends successfully. I doubt this should be an issue with the SMS app you are using, but I just want to make sure. If it is successful, I may attempt to re-initialize the Twilio number to check the encoding that the message is received as.

**Comment by fierytechknowhows** [comment] 2023-02-11 20:48
Yep it still showed 41/3 in Google messages

**Comment by lukeaschenbrenner** [comment] 2023-02-15 01:47
@fierytechknowhows ,
I've been in touch with Samsung Developer Technical Support and they are asking for some information in order to further understand the bug. I've created a [new build](https://drive.google.com/file/d/1q0FidiZ5W2EoUmpixwTjWczsqJ4Fr581/view) of the SMS Test Sender app that logs information a little better. If you can, please screen record yourself all the way from when you first open the app to when the operation completes (I have changed it so it will tell you when all texts are sent). You will be provided with a button to copy some log info; please press the button and paste it into a response here. Also, attach the screen recording here or email it to my personal email (available in GitHub profile). Finally, please include your phone's build number (I am told that on your phone, it should be found under Settings > About Phone > Software Information > Build Number). 
Thank you very much! I'm glad to see that Samsung was responsive to the issue, so if everything is as expected and it is an OS-level issue, you should see a software update eventually roll out.

**Comment by fierytechknowhows** [comment] 2023-02-15 18:23
It showed more failed characters than last time: £, ¥, è, Γ, Λ, Ω, Π, Ψ, Σ, Θ, Ξ, Φ I tested them each and they all still showed 41/3. 
![Screenshot_20230215_073502_SMS Test Sender](https://user-images.githubusercontent.com/19141632/219065068-890f0e8e-a754-41ef-83cb-c04d5fbf65ba.jpg)
this is the build number: TP1A.220624.014
Here is the log info:  
[character: £ result_code: 1 supplied_error_code_or_-1: -1]
 [character: ¥ result_code: 1 supplied_error_code_or_-1: -1]
 [character: è result_code: 1 supplied_error_code_or_-1: -1]
 [character: Γ result_code: 1 supplied_error_code_or_-1: -1]
 [character: Λ result_code: 1 supplied_error_code_or_-1: -1]
 [character: Ω result_code: 1 supplied_error_code_or_-1: -1]
 [character: Π result_code: 1 supplied_error_code_or_-1: -1]
 [character: @ result_code: -1 supplied_error_code_or_-1: -1]
 [character: Ψ result_code: 1 supplied_error_code_or_-1: -1]
 [character: Σ result_code: 1 supplied_error_code_or_-1: -1]
 [character: Θ result_code: 1 supplied_error_code_or_-1: -1]
 [character: $ result_code: -1 supplied_error_code_or_-1: -1]
 [character: Ξ result_code: 1 supplied_error_code_or_-1: -1]
 [character: Φ result_code: 1 supplied_error_code_or_-1: -1]

**Comment by lukeaschenbrenner** [comment] 2023-02-15 21:13
@fierytechknowhows Thanks for the reply. That's very valuable information, because although I am not implementing those Greek characters currently in TxtNet Browser, I had plans to add support for them in the future. It looks like your embed ended up as an image and not a video file, is there any way you can upload the video to a cloud storage provider or email me the video directly? Support was specific in mentioning they wanted a video that demonstrated the bug.

**Comment by fierytechknowhows** [comment] 2023-02-16 04:02
I actually think the problem is Verizon now because i used Samsung's remote test lab for Developers which allows you to remotely connect to devices for testing and I connected to an S20 FE 5G running android 13 like mine. In Samsung messages it showed 0/1 for each character. I also used my old Galaxy Note 5 which is running android 7 and it used to be on verizon until it was deactivated when I upgraded. But it still showed 41/3 on the Note 5 in the default messages app so I actually think it's Verizon now.

**Comment by fierytechknowhows** [comment] 2023-02-16 04:05
But here's the video just in case an update from Samsung could still fix it.

https://user-images.githubusercontent.com/19141632/219265898-b1e98ddb-30c5-4a66-b09c-79f6b7561324.mp4

**Comment by lukeaschenbrenner** [comment] 2023-02-16 17:19
> I actually think the problem is Verizon now because i used Samsung's remote test lab for Developers which allows you to remotely connect to devices for testing and I connected to an S20 FE 5G running android 13 like mine except there wasn't a carrier tied to it. In Samsung messages it showed 0/1 for each character. I also used my old Galaxy Note 5 which is running android 7 and it used to be on verizon until it was deactivated when I upgraded. But it still showed 41/3 on the Note 5 in the default messages app so I actually think it's Verizon now.

That is very interesting, thank you for letting me know. It's quite possible that it is related to the carrier-branded nature of the phones. Either this is a very long-standing OS issue that has existed since at least Android 7, or this issue is somehow present carrier-side on any smartphone, regardless of brand. A surefire way to test this theory would be to insert your SIM into an unlocked smartphone still compatible with Verizon, and checking the character limit there. Of course, it's unreasonable to expect you to have access to one of those to test. I've replied to Samsung with the information you've provided, so hopefully they will be able to track down the issue on their end. I will update you as soon as I receive a substantial response from Samsung. Thank you again for helping me test this issue!

**Comment by lukeaschenbrenner** [comment] 2023-02-17 05:28
@fierytechknowhows I have received a message from developer support at Samsung:
"We are requesting the complete build number of the device. The user has omitted the last part of the Build Number. Please provide us complete build number of the device. It would be something like TP1A.220624.014.G781VXXXXXXXX."
I believe you may have only copied the part of the build number that shows up in the app. That was my mistake, as I did not make it clear that the build number displayed was not the full build number. You can hopefully find the full build number in Settings > About Phone > Software Information > Build Number. Thanks again.

**Comment by fierytechknowhows** [comment] 2023-02-17 05:40
Oh ok here's the full build number: TP1A.220624.014.G781VSQS7GWA1

**Comment by fierytechknowhows** [comment] 2023-02-22 17:10
So what's the status with Samsung?

**Comment by lukeaschenbrenner** [comment] 2023-02-23 00:26
@fierytechknowhows I've been told the issue has been forwarded to the relevant team at Samsung and they are working to reproduce the issue. I'll provide you with more details as soon as they're available!

**Comment by lukeaschenbrenner** [comment] 2023-02-23 19:35
@fierytechknowhows I received a response from Samsung support. The software engineer I spoke with said that their team "tested every character you mentioned ( £, ¥, è, Γ, Λ, Ω, Π, Ψ, Σ, Θ, Ξ, Φ ) in message apps (both Samsung and Google messages) and all of them fit into a single 160 character message on the same software version you mentioned (G781VSQS7GWA1)". Because they are unable to reproduce the issue you're experiencing, they are asking you to create a dumpstate log file so that they can analyze your specific case. Here are the steps that support provided me:

1. Dial *#9900#, Delete Dumpstate/logcat
2. Dial *#9900#, and Select Debug Level to MID. This restarts the device
3. Reproduce the issue (open the Test SMS Sender app and attempt to run the tests)
4. Again dial *#9900# and press “Run Dumpstate/logcat”
5. When it is finished press “Copy To SD Card (include CP Ramdump)
6. Now, use a file explorer to find the "log" folder on the root of the user filesystem. That directory should contain the dumpstate log file generated, having the name format: dumpState_<DEVICE MODEL>_<TIMESTAMP>

Please upload this log file to a file hosting service like Google Drive so that I am able to download it and forward it to the support team (or simply create a temporary GitHub repo and place the file in there).

**Comment by fierytechknowhows** [comment] 2023-02-24 14:36
there was a .zip and .log file and I didn't know which one to send so I put both. I'm guessing only the .log file is needed though.
https://drive.google.com/drive/folders/1HvjUwL_wNk1c4dtE_yZo0DTTIYBCS71_?usp=share_link

**Comment by fierytechknowhows** [comment] 2023-02-24 14:44
there was a .zip file and .log file with that name so I put both in there just in case but I'm guessing that only the .log file is needed.
https://drive.google.com/drive/folders/1HvjUwL_wNk1c4dtE_yZo0DTTIYBCS71_?usp=share_link

**Comment by lukeaschenbrenner** [comment] 2023-03-07 23:15
@fierytechknowhows Thanks for the help. I have finally received a response back from Samsung. They believe, like you suggested, that this is because of the network and that this is working as intended, because CDMA networks using CDMA2000 technologies somehow only support ASCII encoding, and not the GSM-7 alphabet. According to [Wikipedia](https://en.wikipedia.org/wiki/List_of_CDMA2000_networks), Verizon, US Cellular, and Cellcom are the only US carriers still in operation that originated/support CDMA technology. Because of this, any smartphone using one of these carriers would not be able to run TxtNet Browser in its current state. Even though this is the same number of bits, because ASCII has 33 control characters, they go entirely wasted and are not representable without falling back to UCS-2 encoding. However, of course, this only applies to CDMA2000 (and by extension cdmaOne) technology, which was designed for 3G and 2G networks. According to Verizon's [open development 4G SMS requirements](https://opendevelopment-staging.verizonwireless.com/content/dam/opendevelopment/pdf/OpenAccessReq/LTE-SMS_REQ_MAR2016.pdf) (section 5.1.2.2.3), all smartphones using SMS over 4G should support message formats in both 3GPP2 and 3GPP standards. So, it seems that since Verizon has entirely shut down its CDMA network, the only reason that messages are encoding as ASCII is because Android queries the IMS to see if it supports 3GPP2, and if it does, defaults to CDMA encoding. If Verizon also does support 3GPP GSM-7 alphabet like they say in their document when messaging over 4G, then it might actually be a "bug" in Android to encode any control code ASCII character as whitespace. I have messaged Samsung back to see if they can test this theory and possibly fix the bug. 

In the meantime, can you download the [newest build](https://drive.google.com/file/d/1OOjkFpJDEtIXNncR3K2MPoIZ96hKdG8b/view?usp=sharing) of SMS Test Sender and run it again? Ideally, please try it twice, once using the default phone number, and another time using a phone number you know is subscribed to Verizon. Please copy both results to clipboard and share them! (If they are too long, you might want to consider just putting them into pastebin and sending a pastebin link over.)
Thanks again.

**Comment by fierytechknowhows** [comment] 2023-03-08 01:01
It gave the same for both times [character: £ result_code: 1 supplied_error_code_or_-1: -1]
 [character: @ result_code: -1 supplied_error_code_or_-1: -1]
 [character: ¥ result_code: 1 supplied_error_code_or_-1: -1]
 [character: $ result_code: -1 supplied_error_code_or_-1: -1]
 [character: è result_code: 1 supplied_error_code_or_-1: -1]
 [character: Γ result_code: 1 supplied_error_code_or_-1: -1]
 [character: Λ result_code: 1 supplied_error_code_or_-1: -1]
 [character: Ω result_code: 1 supplied_error_code_or_-1: -1]
 [character: Π result_code: 1 supplied_error_code_or_-1: -1]
 [character: Ψ result_code: 1 supplied_error_code_or_-1: -1]
 [character: Σ result_code: 1 supplied_error_code_or_-1: -1]
 [character: Θ result_code: 1 supplied_error_code_or_-1: -1]
 [character: Ξ result_code: 1 supplied_error_code_or_-1: -1]
 [character: Φ result_code: 1 supplied_error_code_or_-1: -1]

**Comment by lukeaschenbrenner** [comment] 2023-03-08 03:36
Hmm... That's not what I would have expected the output to be. There should be more logs inside {{ }} brackets, for every message that sent successfully (just the @ and the $). If you haven't before can you try uninstalling and reinstalling the app? It's possible that maybe I uploaded an old version, but I'm pretty sure I didn't. If that doesn't work, I'll try more troubleshooting tomorrow.

**Comment by lukeaschenbrenner** [comment] 2023-03-08 03:39
For reference, this is what it looks like when I run it (granted, I have no errors since all my messages send successfully).

```
 [character: @ result_code: -1 supplied_error_code_or_-1: -1]
 {{format: 3gpp}}
 {{delivery status for ID#1: [0], protocol identifier: [0], SMSC number: +12063130055}}
 [character: £ result_code: -1 supplied_error_code_or_-1: -1]
 [character: $ result_code: -1 supplied_error_code_or_-1: -1]
 [character: ¥ result_code: -1 supplied_error_code_or_-1: -1]
 {{format: 3gpp}}
 {{delivery status for ID#2: [0], protocol identifier: [0], SMSC number: +14054720057}}
 [character: è result_code: -1 supplied_error_code_or_-1: -1]
 [character: Γ result_code: -1 supplied_error_code_or_-1: -1]
 [character: Λ result_code: -1 supplied_error_code_or_-1: -1]
 {{format: 3gpp}}
 {{delivery status for ID#3: [0], protocol identifier: [0], SMSC number: +14054720105}}
 [character: Ω result_code: -1 supplied_error_code_or_-1: -1]
 [character: Π result_code: -1 supplied_error_code_or_-1: -1]
 [character: Ψ result_code: -1 supplied_error_code_or_-1: -1]
 {{format: 3gpp}}
 {{delivery status for ID#4: [0], protocol identifier: [0], SMSC number: +12063130078}}
 [character: Σ result_code: -1 supplied_error_code_or_-1: -1]
 {{format: 3gpp}}
 {{delivery status for ID#5: [0], protocol identifier: [0], SMSC number: +14054720105}}
 [character: Θ result_code: -1 supplied_error_code_or_-1: -1]
 [character: Ξ result_code: -1 supplied_error_code_or_-1: -1]
 [character: Φ result_code: -1 supplied_error_code_or_-1: -1]
 {{format: 3gpp}}
 {{delivery status for ID#6: [0], protocol identifier: [0], SMSC number: +12063130079}}
...
```

**Comment by fierytechknowhows** [comment] 2023-03-08 04:11
[character: £ result_code: 1 supplied_error_code_or_-1: -1]
 [character: @ result_code: -1 supplied_error_code_or_-1: -1]
 [character: ¥ result_code: 1 supplied_error_code_or_-1: -1]
 [character: $ result_code: -1 supplied_error_code_or_-1: -1]
 [character: è result_code: 1 supplied_error_code_or_-1: -1]
 {{format: 3gpp2}}
 {{delivery status for ID#1: [131072], protocol identifier: [0], SMSC number: +17632692641}}
 [character: Γ result_code: 1 supplied_error_code_or_-1: -1]
 [character: Λ result_code: 1 supplied_error_code_or_-1: -1]
 {{format: 3gpp2}}
 {{delivery status for ID#2: [131072], protocol identifier: [0], SMSC number: +17632692641}}
 [character: Ω result_code: 1 supplied_error_code_or_-1: -1]
 [character: Π result_code: 1 supplied_error_code_or_-1: -1]
 [character: Ψ result_code: 1 supplied_error_code_or_-1: -1]
 [character: Σ result_code: 1 supplied_error_code_or_-1: -1]
 [character: Θ result_code: 1 supplied_error_code_or_-1: -1]
 [character: Ξ result_code: 1 supplied_error_code_or_-1: -1]
 [character: Φ result_code: 1 supplied_error_code_or_-1: -1]

**Comment by lukeaschenbrenner** [comment] 2023-03-09 06:02
@fierytechknowhows Thanks for the info. Unfortunately Samsung Support has reached out to me and said that they are no longer pursuing this issue as it is considered intended behavior. I may have luck in contacting Google to review the CDMA SMS implementation of AOSP, but other than that, there is little else that can be done. I have been informed that all newer Samsung smartphones such as the Galaxy S23 no longer support CDMA provisioning and should work fine with Version using TxtNet. Because of this, I will be closing this issue for now. It only affects a small subset of users on a few carriers, so it's not an immediate priority. The one thing you can still try is to call Verizon and ask for your mobile service to be provisioned as "CDMA-less". It's a setting on their end that disables legacy 3G/2G CDMA support which is what causes this bug. This may be all it takes to disable the weird behavior caused by a query to support 3GPP2. If you do end up doing that, please let me know because then there will at least be a confirmed solution to this issue.
Thanks for all your support throughout this entire process.

**Closed by lukeaschenbrenner** 2023-03-09 06:02 UTC
Labels: bug

**Comment by lukeaschenbrenner** [comment] 2023-03-09 06:14
Just to follow up, it looks like according to this [Reddit thread](https://www.reddit.com/r/verizon/comments/mpvve5/cdmaless_provisioning_roaming_questions/) the provisioning as CDMA-less method is almost definitely what you need to fix this issue. If you can, please try to do it, reboot your phone, and test again.

**Comment by fierytechknowhows** [comment] 2023-03-09 18:34
They said they didn't have a cdma-less setting on their end

**Comment by lukeaschenbrenner** [comment] 2023-03-09 20:31
@fierytechknowhows 
Thanks for checking. According to online forums you have to ask to talk with Network Tech. If they aren't familiar with CDMA-less, you need to ask to be transferred to the "direct tech". Ask them to add the CDMA-less feature to your account. Some Verizon representatives aren't familiar with the feature. I've done this personally when I still had Verizon a few years back, but it took talking with 3 reps before someone knew what I was talking about. Sorry for the troubles but I appreciate you looking into this.

**Comment by fierytechknowhows** [comment] 2023-03-10 02:52
Could you try making it send messages as mms messages

**Comment by fierytechknowhows** [comment] 2023-03-10 05:22
They knew what i was talking about but they still didn't have an option enable cdma-less saying its supposed to be enabled automatically.

**Comment by lukeaschenbrenner** [comment] 2023-03-10 16:47
Okay, thanks for letting me know. Sadly there isn't anything else I can do right now. Like I said I will try to contact Google to see if they can look into possibly fixing that part of AOSP, but otherwise my only alternative would be to enable an ASCII-only backup mode in the app. I'm trying to avoid MMS because that essentially works through data as well, even though it's originally sent through SMS channels. If anyone else has Verizon service and could comment if they are able to send messages using the SMS Test Sender app, that would be very useful. I'm sorry that you won't be able to use TxtNet Browser right now and I want to enable as wide of compatibility as possible, so I will update this issue if an ASCII-only mode is released or if the issue is fixed on AOSP. Thanks again for all the help, I appreciate the time you've dedicated to tracking down this issue.
